name: Chris Watts
favicon: null
layout_spectrum: 0.94171
typography_spectrum: 0.78293
title: ' The  Creationist   âˆ†'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f1d1e'
    - '#eed82d'
    - '#22579d'
    - '#950d19'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
